version: '2.2'
services:
    app:
        container_name: museum_booking_app
        restart: always
        build: ./
        ports:
            - "8080:8080"
        volumes: 
            - .:/usr/app
        links: 
            - mongo
    mongo:
        container_name: mongo_db
        image: mongo
        ports: 
            - "27017:27017"
            
